[package]
name = "precompiles-ed25519"
version = "0.1.0"
edition = "2024"

[dependencies]
bobcat-sdk = { version = "0.7.4", features = ["panic-revert"] }
array-concat = { version = "0.5.5", default-features = false }
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["digest"] }
sha2 = { version = "0.10.9", default-features = false }

[features]
std = ["bobcat-sdk/std"]

[dev-dependencies]
concat-arrays = "0.1.2"
proptest = "1.9.0"
